name: Test Android build
on:
  pull_request:
    branches:
      - master
    paths:
      - 'android/**'
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: android-build-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
      - name: Install node dependencies
        run: yarn
      - name: Build app
        working-directory: android
        run: ./gradlew assembleDebug